spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:orderDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  port: 8082
  servlet:
    context-path: /order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: localhost

services:
  url:
    product-service: http://product-service/product-service/